version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - unused
    - errcheck
    - staticcheck
    - ineffassign
  disable:
    - intrange  # Disable "range over int" modernization suggestions
