package metadata

import (
	"time"
)

// FileHandle is an opaque identifier for a file or directory.
//
// File handles are generated by the repository and used by protocol handlers
// to reference files and directories. They should be:
//   - Unique within the repository
//   - Unpredictable (for security)
//   - Fixed size or variable length (implementation choice)
//
// Protocol handlers may need to translate between FileHandle and protocol-specific
// handle formats (e.g., NFS file handles, SMB file IDs).
type FileHandle []byte

// FileAttr contains the complete metadata for a file or directory.
//
// This structure represents the core attributes common across different
// filesystem protocols. Protocol handlers translate between FileAttr and
// protocol-specific attribute structures.
//
// Time Semantics:
//   - Atime (access time): Updated when file is read
//   - Mtime (modification time): Updated when file content changes
//   - Ctime (change time): Updated when metadata changes (size, permissions, etc.)
//
// Note: Ctime is not "creation time" in Unix semantics - it's the last metadata
// change time. Some protocols (like Windows) have separate creation times which
// may need to be tracked separately.
type FileAttr struct {
	// Type is the file type (regular, directory, symlink, etc.)
	Type FileType

	// Mode contains permission bits and file type
	// Format: Unix permission bits (0o7777 max)
	//   - Bits 0-2: Other permissions (rwx)
	//   - Bits 3-5: Group permissions (rwx)
	//   - Bits 6-8: Owner permissions (rwx)
	//   - Bits 9-11: Special bits (setuid, setgid, sticky)
	Mode uint32

	// UID is the owner user ID
	UID uint32

	// GID is the owner group ID
	GID uint32

	// TODO: Extended attributes for protocol-specific data. Useful, for example, to map Windows ACLs
	// Extended map[string][]byte

	// Size is the file size in bytes
	// For directories: implementation-specific (typically block size)
	// For symlinks: length of target path
	// For special files: 0
	Size uint64

	// Atime is the last access time
	Atime time.Time

	// Mtime is the last modification time (content changes)
	Mtime time.Time

	// Ctime is the last change time (metadata changes)
	Ctime time.Time

	// ContentID is the identifier for retrieving file content from the content repository
	// Empty for directories, symlinks, and special files
	ContentID ContentID

	// LinkTarget is the target path for symbolic links
	// Only valid when Type == FileTypeSymlink
	LinkTarget string
}

// SetAttrs specifies which attributes to update in a SetFileAttributes call.
//
// Each field is a pointer. A nil pointer means "do not change this attribute".
// A non-nil pointer means "set this attribute to the pointed value".
//
// This allows atomic multi-attribute updates with selective modification without
// requiring separate boolean flags for each field.
//
// The server automatically updates Ctime when any attribute changes, so there
// is no Ctime field - clients cannot set Ctime directly.
//
// Example:
//
//	// Change only mode and size
//	attrs := &metadata.SetAttrs{
//	    Mode: metadata.Uint32Ptr(0644),
//	    Size: metadata.Uint64Ptr(1024),
//	    // Other fields are nil = unchanged
//	}
//	err := repo.SetFileAttributes(ctx, handle, attrs)
type SetAttrs struct {
	// Mode is the new permission bits (only lower 12 bits are used)
	// Format: Unix permission bits (0o7777 max)
	// nil = do not change
	Mode *uint32

	// UID is the new owner user ID
	// Only root can change file ownership
	// nil = do not change
	UID *uint32

	// GID is the new owner group ID
	// Only root or owner (if member of target group) can change group
	// nil = do not change
	GID *uint32

	// Size is the new file size in bytes
	// If less than current: truncate (remove trailing content)
	// If greater than current: extend (pad with zeros)
	// If zero: delete all content
	// Cannot be used on directories or special files
	// nil = do not change
	Size *uint64

	// Atime is the new access time
	// nil = do not change
	Atime *time.Time

	// Mtime is the new modification time
	// nil = do not change
	Mtime *time.Time
}

// FileType represents the type of a filesystem object.
//
// These are generic types that map to Unix file types. Protocol handlers
// translate between FileType and protocol-specific type values.
type FileType int

const (
	// FileTypeRegular is a regular file containing data
	FileTypeRegular FileType = iota

	// FileTypeDirectory is a directory (container for other files)
	FileTypeDirectory

	// FileTypeSymlink is a symbolic link (contains a path to another file)
	FileTypeSymlink

	// FileTypeBlockDevice is a block device (disk, partition, etc.)
	FileTypeBlockDevice

	// FileTypeCharDevice is a character device (terminal, serial port, etc.)
	FileTypeCharDevice

	// FileTypeSocket is a Unix domain socket (IPC endpoint)
	FileTypeSocket

	// FileTypeFIFO is a named pipe (FIFO for IPC)
	FileTypeFIFO
)

// ContentID is an identifier for retrieving file content from the content repository.
//
// This is an opaque identifier used to coordinate between metadata and content
// repositories. The format and generation of ContentIDs is implementation-specific.
//
// Example formats:
//   - UUID: "550e8400-e29b-41d4-a716-446655440000"
//   - Hash: "sha256:abcdef123456..."
//   - Path-based: "content/2024/01/15/abc123"
type ContentID string
